# Generated by Django 3.2.8 on 2021-10-31 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_productoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'Shipping Ready'), (3, 'Shipping Completed')], default=0)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_fee', models.IntegerField(default=2500)),
                ('total_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='결제금액')),
                ('payment_method', models.CharField(choices=[('transfer', 'Transfer'), ('kakaopay', 'Kakaopay'), ('naverpay', 'Naverpay')], max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_amount', models.IntegerField(blank=True, null=True, verbose_name='무통장입금 금액')),
                ('transfer_name', models.IntegerField(blank=True, null=True, verbose_name='무통장입금 입금자명')),
                ('transfer_bank', models.IntegerField(blank=True, null=True, verbose_name='무통장입금 은행')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=0)),
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.productoption')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
