# Generated by Django 3.2.8 on 2021-11-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auto_20211031_1018'),
        ('payment', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.productoption'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.order'),
        ),
    ]
