# Generated by Django 3.2.8 on 2021-11-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20211101_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'Shipping Ready'), (3, 'Shipping Completed'), (4, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'Shipping Ready'), (3, 'Shipping Completed'), (4, 'Canceled')], default=0),
        ),
    ]
