# Generated by Django 3.2.8 on 2021-11-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20211101_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='error_message',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='payment.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'Payment Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'Payment Failed'), (3, 'Shipping Ready'), (4, 'Shipping Completed'), (5, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Paid'), (2, 'Payment Failed'), (3, 'Shipping Ready'), (4, 'Shipping Completed'), (5, 'Canceled')], default=0),
        ),
    ]
