# Generated by Django 3.2.8 on 2021-11-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_historicalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='항목별 주문 금액'),
        ),
    ]
