# Generated by Django 3.2.8 on 2021-11-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productoption_additional_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='additional_price',
            new_name='price',
        ),
    ]
