# Generated by Django 3.2.8 on 2021-11-03 09:58

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='price',
            new_name='additional_price',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_directory_path),
        ),
    ]
