# Generated by Django 3.2.8 on 2021-11-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20211103_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='additional_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='productoption',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
