# Generated by Django 3.2.8 on 2021-11-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20211103_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본 여부'),
        ),
    ]
