# Generated by Django 3.2.8 on 2021-11-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_productoption_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.IntegerField(default=2500),
        ),
    ]
